repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      # Go Test
      - id: go-test-repo-mod # targets all modules in repo
        stages: [ push ] # only run tests on push, not on commit

      # Go Vet
      - id: go-vet-repo-mod

      # GoSec
      - id: go-sec-repo-mod # go install github.com/securego/gosec/v2/cmd/gosec@latest

      # Formatters
      - id: go-imports-repo
      - id: go-fumpt-repo # go install mvdan.cc/gofumpt@latest

      # Style Checkers
      - id: go-critic # go install github.com/go-critic/go-critic/cmd/gocritic@latest

      # Go Mod Tidy
      - id: go-mod-tidy-repo
