repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      # Go Test
      - id: go-test-repo-mod # targets all modules in repo

      # Go Vet
      - id: go-vet-repo-mod

      # GoSec
      - id: go-sec-repo-mod # install with `make devenv-init`

      # Formatters
      - id: go-imports-repo
      - id: go-fumpt-repo

      # Style Checkers
      - id: go-critic

      # Go Mod Tidy
      - id: go-mod-tidy-repo
